# This is a basic workflow to help you get started with Actions

name: Pull state Finances

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule: 
    - cron: "0 8 * * *" 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scrape:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # runs the scrapers just for PA for right now. 

      - name: Download PA Campaign finance data
        
          DB_URL_PROD: ${{ secrets.DB_URL_PROD }}
        run: |
          npm install
          node loader --loadType=finance --year=2022 --state=pennsylvania

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
